[package]
name = "ratatui-kit-principle"
version = "0.1.0"
edition = "2024"

[dependencies]
any_key = "0.1.1"
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3.31"
ratatui = "0.29.0"
tokio = { version = "1.45.1", features = ["full"] }
