[package]
name = "ratatui-kit-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full"] }
uuid = { version = "1.17.0", features = ["v4"] }

[lib]
proc-macro = true
